# Generated by Django 5.1 on 2024-09-03 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadRT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('ubicacion_cliente', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.base')),
                ('unidad_rt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.unidadrt')),
            ],
        ),
    ]
