# Generated by Django 5.1 on 2024-09-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_delete_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='direccion',
            field=models.CharField(default='Dirección no especificada', max_length=255),
        ),
    ]
