# Generated by Django 5.1 on 2024-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_base_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unidadrt',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=50),
        ),
    ]
