# Generated by Django 5.1 on 2024-10-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_motivo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='unidad_rt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.unidadrt'),
        ),
    ]
